### GET all games, expected 200
GET http://localhost:8080/api/games HTTP/1.1
Accept: application/json

### GET all games XML, expected 200
GET http://localhost:8080/api/games HTTP/1.1
Accept: application/xml

### DELETE game by id, expected 204
DELETE http://localhost:8080/api/games/1

### DELETE game by id, expected 404
DELETE http://localhost:8080/api/games/1239

### POST game, expected 201
POST http://localhost:8080/api/games
Accept: application/json
Content-Type: application/json

{
    "title": "Team Fortress 2",
    "description": "Team Fortress 2 is a team-based multiplayer first-person shooter video game developed and published by Valve Corporation. It is the sequel to the 1996 mod Team Fortress for Quake and its 1999 remake, Team Fortress Classic.",
    "developerId": 1
}

### POST game, expected 404
POST http://localhost:8080/api/games
Accept: application/json
Content-Type: application/json

{
    "title": "Team Fortress 2",
    "description": "Team",
    "developerId": 9088
}

### POST game, dont allow empty title, expected 400
POST http://localhost:8080/api/games
Accept: application/json
Content-Type: application/json

{
    "title": "",
    "description": "Team",
    "developerId": 1
}

### PATCH Update game, expected 200
PATCH http://localhost:8080/api/games/1
Accept: application/json
Content-Type: application/json

{
    "title": "Counter-Strike 2",
    "description": "For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2.",
    "developerId": "2"
}

### PATCH Update game, expected 404
PATCH http://localhost:8080/api/games/1239
Accept: application/json
Content-Type: application/json

{
    "title": "Counter-Strike 2",
    "description": "For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2.",
    "developerId": "2"
}

### PATCH Update game, missing title, expected 400
PATCH http://localhost:8080/api/games/1
Accept: application/json
Content-Type: application/json

{
    "description": "For"
}

### POST create game, missing developer, expected 400
POST http://localhost:8080/api/games
Accept: application/json
Content-Type: application/json

{
    "title": "For"
}

### POST create game, title too short, expected 400
POST http://localhost:8080/api/games
Accept: application/json
Content-Type: application/json

{
    "title": "C",
    "description": "For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2.",
    "developerId": "2"
}

### POST create game, description too long, expected 400
POST http://localhost:8080/api/games
Accept: application/json
Content-Type: application/json

{
    "title": "Counter-Strike 2",
    "description": "For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2. For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2. For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin.",
    "developerId": "2"
}
