version: '3.8'

services:
  prog5-db:
    image: postgres:16.1-alpine
    # restart: always
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Student1234
      - POSTGRES_DB=prog
    ports:
      - '5443:5432'
    volumes:
      - prog5_pgdata:/var/lib/postgresql/data
  
  prog5-db-test:
    image: postgres:16.1-alpine
    # restart: always
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Student1234
      - POSTGRES_DB=prog
    ports:
      - '5444:5432'
    volumes:
      - prog5_pgdata_test:/var/lib/postgresql/data

volumes:
  prog5_pgdata:
  prog5_pgdata_test:
