server:
    error:
        whitelabel.enabled: true
        include-message: always

spring:
    datasource:
        url: jdbc:postgresql://postgres:5432/prog5
        username: postgres
        password: Student1234
    sql:
        init:
            mode: always

logging:
  level:
    com:
      ross: TRACE
    org:
      hibernate:
        SQL: TRACE
