server:
    error:
        whitelabel.enabled: true
        include-message: always

spring:
    datasource:
        url: jdbc:postgresql://postgres:5432/int4t9
        username: postgres
        password: Student1234
    sql:
        init:
            mode: always

logging:
    level:
        com:
            ross: WARN
        org:
            hibernate:
                SQL: WARN
