version: '3.8'

services:
  # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
  # (Adding the "ports" property to this file will not forward from a Codespace.)

  # Dev Container
  prog5:
    container_name: prog5
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.dev
    # restart: always
    volumes:
      - .:/workspace:cached
      - /home/ross/.ssh:/home/vscode/.ssh
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    expose:
      - "8083"
    ports:
      - "8083:8080"
